print("                 RATING AND COMMENT\n")
rating  = int(input("Please enter the rating out of 10 for our software:    "))
comment = input("Please comment on our software:   ")
print('\n\n')
print("Thank you for rating us, next time we will be even better \n")